//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiddlerHandle.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiddlerHandle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 var anshunxu = arguments[0];
        ///
        ///function getBase64Image(arg1){
        ///	
        ///    var miaoshu = arguments[0];//参数
        ///	if(!miaoshu)
        ///	{
        ///		var el =document.querySelector(&quot;body &gt; div.wrap.captcha-wrap &gt; div.captcha-title&quot;);
        ///		if(el){
        ///			miaoshu = el.textContent;
        ///		}else{
        ///			miaoshu = &quot;按顺序点击：&quot;;
        ///		}
        ///	}
        ///
        ///    var smallImg =document.querySelector(&quot;body &gt; div.wrap.captcha-wrap &gt; div.captcha-title &gt; img&quot;);//小图片
        ///    var bigImg = document.querySelector(&quot;body &gt; div.wrap.captcha-wrap &gt; div.captcha-opera &gt; div &gt; div:nth-chil [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string getBase64Image_tbdj {
            get {
                return ResourceManager.GetString("getBase64Image_tbdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var miaoshuarg = arguments[0];
        /////var imgarg=arguments[1];//传的不是真的 img 图片啊 我靠
        ///
        /////window.frames[&quot;UDBSdkLgn_iframe&quot;][&quot;tcaptcha_iframe&quot;]
        ///function getBase64Image(arg1){
        ///    //var miaoshu = document.getElementsByClassName(&quot;tcaptcha-title&quot;)[0].innerText;  由于是在框架里面 document 切不到指定框架,获取不到指定内容 只能传参数
        ///    var miaoshu = arguments[0];//参数
        ///    var img = document.querySelector(&quot;#tcaptcha-img&quot;);//document.getElementById(&quot;tcaptcha-img&quot;); 
        ///
        ///    var canvas = document.createElement(&quot;canvas&quot;);// 创建一个canvas
        ///    canvas.wi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string getBase64Image_Vtt {
            get {
                return ResourceManager.GetString("getBase64Image_Vtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try{!function(e){function t(){if(/HeadlessChrome/.test(navigator.userAgent)||!navigator.languages||0===navigator.languages.length)return!0;for(var t=[],r=[&quot;webdriver&quot;,&quot;__driver_evaluate&quot;,&quot;__webdriver_evaluate&quot;,&quot; __selenium_evaluate&quot;,&quot;__fxdriver_evaluate&quot;,&quot;__driver_unwrapped&quot;,&quot;__webdriver_unwrapped&quot;,&quot;__selenium_unwrapped&quot;,&quot;__fxdriver_unwrapped&quot;,&quot;_Selenium_IDE_Recorder&quot;,&quot;_selenium&quot;,&quot;calledSelenium&quot;,&quot;_WEBDRIVER_ELEM_CACHE&quot;,&quot;ChromeDriverw&quot;,&quot;driver-evaluate&quot;,&quot;webdriver-evaluate&quot;,&quot;selenium-evaluate&quot;,&quot;webdriverCom [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_5a4da2d {
            get {
                return ResourceManager.GetString("hydevice_5a4da2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try{!function(e){function t(){if(/HeadlessChrome/.test(navigator.userAgent)||!navigator.languages||0===navigator.languages.length)return!0;const t=[],r=[&quot;webdriver&quot;,&quot;__driver_evaluate&quot;,&quot;__webdriver_evaluate&quot;,&quot; __selenium_evaluate&quot;,&quot;__fxdriver_evaluate&quot;,&quot;__driver_unwrapped&quot;,&quot;__webdriver_unwrapped&quot;,&quot;__selenium_unwrapped&quot;,&quot;__fxdriver_unwrapped&quot;,&quot;_Selenium_IDE_Recorder&quot;,&quot;_selenium&quot;,&quot;calledSelenium&quot;,&quot;_WEBDRIVER_ELEM_CACHE&quot;,&quot;ChromeDriverw&quot;,&quot;driver-evaluate&quot;,&quot;webdriver-evaluate&quot;,&quot;selenium-evaluate&quot;,&quot;webdriverComma [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_7317c16 {
            get {
                return ResourceManager.GetString("hydevice_7317c16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try{!function(e){function t(){if(/HeadlessChrome/.test(navigator.userAgent)||!navigator.languages||0===navigator.languages.length)return!0;for(var t=[],r=[&quot;webdriver&quot;,&quot;__driver_evaluate&quot;,&quot;__webdriver_evaluate&quot;,&quot; __selenium_evaluate&quot;,&quot;__fxdriver_evaluate&quot;,&quot;__driver_unwrapped&quot;,&quot;__webdriver_unwrapped&quot;,&quot;__selenium_unwrapped&quot;,&quot;__fxdriver_unwrapped&quot;,&quot;_Selenium_IDE_Recorder&quot;,&quot;_selenium&quot;,&quot;calledSelenium&quot;,&quot;_WEBDRIVER_ELEM_CACHE&quot;,&quot;ChromeDriverw&quot;,&quot;driver-evaluate&quot;,&quot;webdriver-evaluate&quot;,&quot;selenium-evaluate&quot;,&quot;webdriverCom [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_7f9c2fe {
            get {
                return ResourceManager.GetString("hydevice_7f9c2fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try{!function(e){function t(){var t=[];if(/HeadlessChrome/.test(navigator.userAgent)||!navigator.languages||0===navigator.languages.length)return t.push(&quot;homeless&quot;),t.toString();for(var r=[&quot;webdriver&quot;,&quot;__driver_evaluate&quot;,&quot;__webdriver_evaluate&quot;,&quot; __selenium_evaluate&quot;,&quot;__fxdriver_evaluate&quot;,&quot;__driver_unwrapped&quot;,&quot;__webdriver_unwrapped&quot;,&quot;__selenium_unwrapped&quot;,&quot;__fxdriver_unwrapped&quot;,&quot;_Selenium_IDE_Recorder&quot;,&quot;_selenium&quot;,&quot;calledSelenium&quot;,&quot;_WEBDRIVER_ELEM_CACHE&quot;,&quot;ChromeDriverw&quot;,&quot;driver-evaluate&quot;,&quot;webdriver-evaluate&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_8290851 {
            get {
                return ResourceManager.GetString("hydevice_8290851", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var myjiqima = &apos;&apos;;
        ///try {
        ///    !function(e) {
        ///        function t() {
        ///            var t = [];
        ///            if (/HeadlessChrome/.test(navigator.userAgent) || !navigator.languages || 0 === navigator.languages.length)
        ///                return t.push(&quot;homeless&quot;),
        ///                t.toString();
        ///            for (var r = [&quot;webdriver&quot;, &quot;__driver_evaluate&quot;, &quot;__webdriver_evaluate&quot;, &quot; __selenium_evaluate&quot;, &quot;__fxdriver_evaluate&quot;, &quot;__driver_unwrapped&quot;, &quot;__webdriver_unwrapped&quot;, &quot;__selenium_unwrapped&quot;, &quot;__fxdriver_unwrap [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_8290851_Get {
            get {
                return ResourceManager.GetString("hydevice_8290851_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try{!function(e){function t(){this.getDeviceId=function(){return getSdid()};var e=&quot;&quot;;this.getCommmonInfo=function(){if(e)return e;var t=getCommmonInfo();try{e=btoa(unescape(encodeURIComponent(t)))}catch(n){}return e}}var n={hexEncode:function(e){return this.toHex(this.core(this.toArray(e)))},toArray:function(e){for(var t=(e.length+8&gt;&gt;6)+1,n=new Array(16*t),r=0;16*t&gt;r;r++)n[r]=0;for(r=0;r&lt;e.length;r++)n[r&gt;&gt;2]|=e.charCodeAt(r)&lt;&lt;24-8*(3&amp;r);return n[r&gt;&gt;2]|=128&lt;&lt;24-8*(3&amp;r),n[16*t-1]=8*e.length,n},toHex:function( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_b3e78a1 {
            get {
                return ResourceManager.GetString("hydevice_b3e78a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 try{!function(e){function t(){_keyStr=&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=&quot;,this.encode=function(e){var t,r,n,a,o,i,c,d=&quot;&quot;,f=0;for(e=_utf8_encode(e);f&lt;e.length;)t=e.charCodeAt(f++),r=e.charCodeAt(f++),n=e.charCodeAt(f++),a=t&gt;&gt;2,o=(3&amp;t)&lt;&lt;4|r&gt;&gt;4,i=(15&amp;r)&lt;&lt;2|n&gt;&gt;6,c=63&amp;n,isNaN(r)?i=c=64:isNaN(n)&amp;&amp;(c=64),d=d+_keyStr.charAt(a)+_keyStr.charAt(o)+_keyStr.charAt(i)+_keyStr.charAt(c);return d},this.decode=function(e){var t,r,n,a,o,i,c,d=&quot;&quot;,f=0;for(e=e.replace(/[^A-Za-z0-9\+\/\=]/g,&quot;&quot;);f&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hydevice_c9d7e69 {
            get {
                return ResourceManager.GetString("hydevice_c9d7e69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Object.defineProperty(navigator, &apos;webdriver&apos;, {
        ///      get: () =&gt; undefined
        ///    }) 的本地化字符串。
        /// </summary>
        internal static string webdriverPingBi {
            get {
                return ResourceManager.GetString("webdriverPingBi", resourceCulture);
            }
        }
    }
}
